<Project>

    <PropertyGroup>
        <Version>2.6.1</Version>
        <TargetFramework>net48</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <AnalysisMode>AllEnabledByDefault</AnalysisMode>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    </PropertyGroup>

</Project>
