// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ProjectFilter
{
    internal sealed partial class Vsix
    {
        public const string Id = "ProjectFilter.76800882-6e41-4df7-9db4-1945655b2620";
        public const string Name = "Project Filter";
        public const string Description = @"Quickly load and unload projects.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "reduckted";
        public const string Tags = "";
    }
}
