// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ProjectFilter
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string ProjectFilterPackageString = "ef4f8800-6a91-41d3-9c6b-44d13fc9c487";
        public static Guid ProjectFilterPackage = new Guid(ProjectFilterPackageString);

        public const string UICONTEXT_SolutionExistsAndFullyLoadedString = "10534154-102d-46e2-aba8-a6bfa25ba0be";
        public static Guid UICONTEXT_SolutionExistsAndFullyLoaded = new Guid(UICONTEXT_SolutionExistsAndFullyLoadedString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int FilterProjectsCommand = 0x0001;
    }
}