name: Publish Extension

on:
    release:
        types: [published]

jobs:
    publish:
        runs-on: windows-latest

        env:
            Configuration: Release
            DeployExtension: false

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup MSBuild
              uses: microsoft/setup-msbuild@v1.0.2
              with:
                  vs-version: "[16.9,16.10)"

            - name: Build
              run: msbuild /t:Rebuild /Restore /v:Minimal

            - name: Test
              run: msbuild tests/ProjectFilter.UnitTests /t:Test /v:Minimal

            - name: Publish
              uses: cezarypiatek/VsixPublisherAction@0.2
              with:
                  extension-file: source\ProjectFilter\bin\Release\ProjectFilter.vsix
                  publish-manifest-file: publish.json
                  personal-access-code: ${{ secrets.PUBLISHER_TOKEN }}
